name: AnvilLogin
version: ${project.version}
main: io.github.portlek.anvillogin.AnvilLogin
authors: [portlek, vcele]
description: Login into server with anvil gui and global password.
api-version: 1.20